### ISSUE TITLE
Webpack-cli 4.9.0

### ISSUE THREAD

**Issue by SimonMulquin** [Mohammad-Faisal/react-typescript-template-from-scratch#1]
Hey, thanks a lot for this Mohammad,

I had to replace webpack-cli version by 4.9.0 in order to start the dev server, otherwise I had an issue with the serve command.

$ webpack serve --config webpack.config.js --env env=development
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function

With this change it seems everythings works fine.

**Comment by Mohammad-Faisal** [comment]
Thanks, @SimonMulquin for pointing that out. 

I have updated the project with the latest version of both webpack and webpack-cli. 
I have tested that it's running fine now.
